---
title: "الارهاب في الساحل"
description: |
  Below is a short article I wrote in arabic regarding terrorism in the Sahel. 
author:
  - name: Jayde Lyon
date: '04/28/2021'
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

على مدى السنوات العشر الماضية، كانت زيارة في العنف والإرهاب في جميع انحاء منطقة الساحل في افريقيا. وتشمل هذه المنطقة بلدان نيجيريا والنيجر وتشاد وبوركينو فاسو ومالي. وقد التقي هذه الحملات الإرهابية التي يقوم بها المتشددون وجماعات الإرهاب الإسلامي بالعديد من المساعدات الدولية وعمليات مكافحة الإرهاب. لكن معظم هذه العمليات كانت برئيسة دول غربية بدلا من الدول المجاورة في افريقيا والشرق الأوسط. سالت نفسي، ما هي اثار هده الجهود.
 
وقد تمكن الارهابيون من استغلال الاختلافات العرقية بين المدنيين والسيطرة على المناطق التي لا تسيطر عليها الدولة سيطرة قوية.  وقد أدى ذلك الى تحويل الملايين الى مهاجرين ولاجئين والاف القتلى. بادز الجماعتين ارهابيتين في المنطقة هما بوكو حرام والقاعدة في بلاد المغرب الإسلامي. قتلت بوكو حرام العديد من الأشخاص في هجمات مسلحة وتفجيرات وتفجيرات انتحارية. كما اختطفت بوكو حرام العديد من البنات في سن الدراسة وهددت التعليم في شمال نيجيريا. تنظيم القاعدة في بلاد المغرب الإسلامي مشابه جدا، وقد قام بعمليات قنبلة مستمرة جميع انحاء منطقة الساحل.
 
ومع ذلك، فقد تبين ان العمليات العسكرية الدولية والحكومية تسببت في مقتل عدد من المدنيين اكبر من عدد الجماعات الإرهابية. وقد أدى ذلك أيضا الى سهولة تجنيد المنظمات الإرهابية، حيث تقتل الحكومة مدييها. وقتيل ان القوات الدولية في المنطقة ارتكبت انتهاكات لحقوق الانسان ضد المدنيين، بما في ذلك الاغتصاب والقتل خلال العمليات. ولا يمكن للمجتمعات المحلية ان تعتمد على المنظمات الإرهابية او القوات الدولية. هذا العام انضمت الامارات أخيرا الى عمليات مكافحة الإرهاب في منطقة الساحل الافريقي. وهم في معظمها لا يقدمون سوى الدعم الجوي ولكنهم يأملون في تحقيق الامن في المنطقة. كما ستجلب الرحلات مساعدات إنسانية ولقاحات من الطراز كوفيد ١٩.
 
اعتفد انه من المهم جدا ان تشارك البلدان الإقليمية في افريقيا والشرق الأوسط في مكافحة الإرهاب في منطقة الساحل. الحدود في المنطقة باسرها مائه جدا العنف يمكن ان ينتقل بسهولة الى بلدان أخرى. يجب على الجميع ان يفعلوا ما هو افضل.






